# Generated by Django 6.0 on 2026-01-24 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cashier', 'Cashier'), ('permit', 'Permit'), ('registrar', 'Registrar')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('windows', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('average_service_time', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('queue_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified (Within 5)'), ('serving', 'Currently Serving'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('ticket_date', models.DateField()),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_window', models.CharField(blank=True, max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='queueing.service')),
            ],
            options={
                'verbose_name': 'Queue Ticket',
                'verbose_name_plural': 'Queue Tickets',
                'ordering': ['service', 'ticket_date', 'queue_number'],
                'unique_together': {('service', 'queue_number', 'ticket_date')},
            },
        ),
    ]
