# Generated by Django 6.0 on 2026-02-02 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('cashier', 'Cashier'), ('permit', 'Permit'), ('registrar', 'Registrar'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('current_queue_number', models.PositiveIntegerField(default=0)),
                ('last_queue_reset', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['ticket_date', 'queue_number']},
        ),
        migrations.AddField(
            model_name='service',
            name='current_queue_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='last_queue_reset',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_group',
            field=models.CharField(blank=True, choices=[('cashier', 'Cashier'), ('permit', 'Permit'), ('registrar', 'Registrar')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='service',
            name='windows',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('serving', 'Currently Serving'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='served_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_tickets', to='queueing.window'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='window',
            field=models.ForeignKey(blank=True, help_text='Specific window for registrar/permit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='queueing.window'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('service_group', 'queue_number', 'ticket_date'), ('window', 'queue_number', 'ticket_date')},
        ),
        migrations.AddField(
            model_name='service',
            name='windows',
            field=models.ManyToManyField(blank=True, related_name='services', to='queueing.window'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_window',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='service',
        ),
    ]
