# Generated by Django 6.0 on 2026-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='current_queue_number',
        ),
        migrations.RemoveField(
            model_name='service',
            name='last_queue_reset',
        ),
        migrations.AlterField(
            model_name='servicewindow',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicewindow',
            name='window_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
