# Generated by Django 6.0 on 2026-02-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0002_remove_service_current_queue_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='current_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_manning_staff', to='queueing.servicewindow'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
