# Generated by Django 6.0 on 2026-02-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0003_staffprofile_current_window_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='current_window',
        ),
    ]
