# Generated by Django 6.0 on 2026-03-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0004_remove_staffprofile_current_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
