# Generated by Django 6.0 on 2026-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0005_alter_service_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sms_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
