# Generated by Django 6.0 on 2026-03-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0008_activesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSession',
        ),
    ]
