# Generated by Django 6.0 on 2026-03-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0009_delete_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_accepting_tickets',
            field=models.BooleanField(default=True),
        ),
    ]
