# Generated by Django 6.0 on 2026-03-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0010_service_is_accepting_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_accepting_tickets',
        ),
    ]
