# Generated by Django 6.0 on 2026-03-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0010_service_auto_schedule_fields'),
        ('queueing', '0011_remove_service_is_accepting_tickets'),
    ]

    operations = [
    ]
