# Generated by Django 6.0 on 2026-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0012_merge_20260318_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='auto_cutoff_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='auto_start_time',
        ),
        migrations.AddField(
            model_name='service',
            name='closing_time',
            field=models.TimeField(blank=True, default='16:50', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='opening_time',
            field=models.TimeField(blank=True, default='07:00', null=True),
        ),
    ]
