# Generated by Django 6.0 on 2026-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0014_alter_service_auto_schedule_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='closing_time',
            new_name='auto_cutoff_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='opening_time',
            new_name='auto_start_time',
        ),
        migrations.AlterField(
            model_name='service',
            name='auto_schedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
