# Generated by Django 6.0 on 2026-03-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0016_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='auto_cutoff_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='auto_schedule_enabled',
        ),
        migrations.RemoveField(
            model_name='service',
            name='auto_start_time',
        ),
    ]
