# Generated by Django 6.0 on 2026-03-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0017_remove_service_auto_cutoff_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='auto_shutdown_enabled',
            new_name='auto_schedule_enabled',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='opening_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
