# Generated by Django 6.0 on 2026-03-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0018_rename_auto_shutdown_enabled_systemsettings_auto_schedule_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='opening_time',
            field=models.TimeField(default='06:00'),
        ),
    ]
